export enum ActionTypes {
  AUTH_LOG_IN,
  AUTH_LOG_OUT,
  AUTH_REGISTER,
  AUTH_CHECK_LOGIN,
  AUTH_START_CHECK,
  CRUD_SET_DATA,
  ROLES_SET,
  DATA_FETCH_LOADING_START,
  DATA_FETCH_LOADING_STOP,
  DATA_FETCH_SET_MESSAGE,
  DATA_FETCH_CLEAR_MESSAGE
}